kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/manoharreddy0077/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - tag

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add gcc g++
      - go test -p 1 -coverprofile=coverage.txt ./...

  - name: build-linux-dev
    image: golang:alpine
    when:
      branch:
        - main
      event:
        - push
    commands:
      - apk add gcc g++
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/linux/amd64/io-dicom cmd/io-dicom/main.go
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/linux/amd64/compare cmd/compare/main.go

  - name: docker-dev
    image: plugins/docker
    privileged: true
    when:
      branch:
        - main
      event:
        - push
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      auto_tag: true
      # platforms:
      #   - linux/amd64
      #   - darwin/arm64
      registry: ghcr.io
      repo: ghcr.io/manoharreddy0077/${DRONE_REPO_NAME}
      tags: dev

  - name: build-linux-latest
    image: golang:alpine
    when:
      branch:
        - main
      event:
        - tag
    commands:
      - apk add gcc g++
      - go build -v -a -ldflags "-X main.version=build.${DRONE_TAG}" -o build/linux/amd64/io-dicom cmd/io-dicom/main.go
      - go build -v -a -ldflags "-X main.version=build.${DRONE_TAG}" -o build/linux/amd64/compare cmd/compare/main.go
  
  - name: docker-latest
    image: plugins/docker
    privileged: true
    when:
      branch:
        - main
      event:
        - tag
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      auto_tag: true
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
      registry: ghcr.io
      repo: ghcr.io/manoharreddy0077/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}
  
  - name: publish
    image: plugins/github-release
    when:
      branch:
        - main
      event:
        - tag
    settings:
      title: "Innovative IO DICOM Tools"
      api_key:
        from_secret: github_token
      files:
        - build/linux/amd64/io-dicom
        - build/linux/amd64/compare
